# Generated by Django 5.2.4 on 2025-09-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('mobile_money', 'Mobile Money'), ('other', 'Other')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='expense', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
